### PR TITLE
update readme to change db_host to mysql

### PR DESCRIPTION
**Pull request by bgreatfit**
Added a step to change the DB_HOST variable in .env to mysql

### CODE REVIEW

**Comment by hanieas** [comment]
Thanks for your PR, but `DB_HOST` should be `db`, that is the name of your service.

**Comment by bgreatfit** [comment]
@hanieas  true, it was a mistake on my part. Also, I believe that running composer install outside the docker environment defeats the purpose of containerization as a composer will depend on the host environment and not on the docker environment libraries

**Comment by hanieas** [comment]
Yeah, thanks.
I really appreciate it.

**Comment by bgreatfit** [comment]
seems  you already added composer

**Pull request closed without merging**
